handle_args: char:2; exception: E2().
----------------
Coverage Report:

__main__: test/exc-TEF_{:d}.py: 12 lines; 4 trivial; 8 traceable; 8 covered; 0 relaxed; 0 ignored; 0 ignored but covered; 0 not covered.
