handle_args: char:2; exception: E2().
----------------
Coverage Report:

__main__: test/exc-TA_{:d}.py: 10 lines; 3 trivial; 7 traceable; 6 covered; 1 relaxed; 0 ignored; 0 ignored but covered; 0 not covered.
